// Mandatory integration suite orchestrator.
//
// Proves that mocks generated by Mockaccino actually compile and run: it
//   1. compiles the extension TS so the backends are available,
//   2. runs *both* backends on the dependency headers (display.h, rng.h):
//      RegexMockaccino -> integration/generated, ClangMockaccino ->
//      integration/generated_clang,
//   3. configures + builds the CMake project with clang (FetchContent pulls
//      GoogleTest) — the same gtest/stub/assert tests are built against each
//      backend's output, so both must produce interchangeable mocks,
//   4. runs the gmock unit tests via ctest, and
//   5. runs the real game_of_life binary for a few generations.
//
// This suite is MANDATORY and never skips: it must actually run and pass.
// Anything that stops it — a missing tool (clang/cmake/ninja/network for the
// GoogleTest download) or a genuine build/test failure — exits non-zero.

const fs = require('fs');
const path = require('path');
const os = require('os');
const { spawnSync } = require('child_process');

const integrationDir = __dirname;
const repoRoot = path.resolve(integrationDir, '..');
const srcDir = path.join(integrationDir, 'src');
const genDir = path.join(integrationDir, 'generated');
const genClangDir = path.join(integrationDir, 'generated_clang');
const buildDir = path.join(integrationDir, 'build');
const templatesDir = path.join(repoRoot, 'templates');

const isWin = process.platform === 'win32';

function run(cmd, args, opts = {}) {
	const res = spawnSync(cmd, args, {
		stdio: 'inherit',
		shell: isWin, // resolve cmake/ctest/npx via PATH + PATHEXT on Windows
		cwd: opts.cwd || integrationDir,
		...opts,
	});
	return res;
}

function fail(message) {
	console.error(`\n[integration] FAILED: ${message}`);
	process.exit(1);
}

// --- 1. compile the extension so out/mockaccino.js is available ---------------
console.log('[integration] 1/5 Compiling extension (tsc)...');
{
	const res = run(isWin ? 'npx.cmd' : 'npx', ['tsc', '-p', '.', '--outDir', 'out'], { cwd: repoRoot });
	if (res.error || res.status !== 0) {
		fail('could not compile the extension with tsc');
	}
}

// --- 2. generate the mocks with Mockaccino (both backends) --------------------
console.log('[integration] 2/5 Generating mocks with Mockaccino (regex + clang)...');
{
	const RegexMockaccino = require(path.join(repoRoot, 'out', 'regex_mockaccino'));
	const ClangMockaccino = require(path.join(repoRoot, 'out', 'clang_mockaccino'));

	const makeConfig = (outputPath) => {
		const values = {
			additionalPreprocessorDirectives: '',
			ignoredFunctionNames: 'main',
			copyright: 'Copyright (c) 2026 Mockaccino integration test.',
			treatLonelyPreprocIfAsActive: true,
			skipFunctionsWithImplicitReturnType: false,
			skipStaticFunctions: true,
			skipExternFunctions: true,
			outputPath,
			// clang backend settings (display.h/rng.h are self-contained, so no
			// extra include or system-header paths are needed).
			clangPath: '',
			includeDirectories: [],
			clangSystemHeaderPaths: [],
			clangExtraArgs: [],
		};
		const cfg = { get: (k) => values[k] };
		cfg.disableDoubleMocking = true;
		return cfg;
	};

	// Generate display.h + rng.h with one backend into outDir; fail on any error.
	const generateWith = (BackendClass, outDir, label) => {
		fs.mkdirSync(outDir, { recursive: true });
		// Silence the orchestrator's chatty logging.
		const log = console.log;
		const warn = console.warn;
		console.log = () => {};
		console.warn = () => {};
		try {
			for (const header of ['display.h', 'rng.h']) {
				const src = path.join(srcDir, header);
				const content = fs.readFileSync(src, 'utf8');
				const uri = { fsPath: src, scheme: 'file' };
				// One instance per header is reused for both outputs.
				const generator = new BackendClass(content, uri, makeConfig(outDir), '0.0.0-test', '', templatesDir);
				const mockResult = generator.mock();
				const stubResult = generator.stub();
				console.log = log;
				console.warn = warn;
				if (mockResult.result !== 0) {
					fail(`${label} mock generation for ${header} returned ${mockResult.result}: ${mockResult.message}`);
				}
				if (stubResult.result !== 0) {
					fail(`${label} stub generation for ${header} returned ${stubResult.result}: ${stubResult.message}`);
				}
				log(`  [${label}] ${header} -> ${mockResult.mock_count} mock(s), ${stubResult.mock_count} stub(s)`);
				console.log = () => {};
				console.warn = () => {};
			}
		} finally {
			console.log = log;
			console.warn = warn;
		}
	};

	// Generate the C++ class mock (sink.hpp) with one backend — mock only (gmock
	// classes have no stub). Produces <name>_mock.hpp.
	const generateCppWith = (BackendClass, outDir, label) => {
		fs.mkdirSync(outDir, { recursive: true });
		const log = console.log;
		const warn = console.warn;
		console.log = () => {};
		console.warn = () => {};
		let result;
		try {
			const src = path.join(srcDir, 'sink.hpp');
			const content = fs.readFileSync(src, 'utf8');
			const uri = { fsPath: src, scheme: 'file' };
			const generator = new BackendClass(content, uri, makeConfig(outDir), '0.0.0-test', '', templatesDir);
			result = generator.mock();
		} finally {
			console.log = log;
			console.warn = warn;
		}
		if (result.result !== 0) {
			fail(`${label} C++ mock generation for sink.hpp returned ${result.result}: ${result.message}`);
		}
		log(`  [${label}] sink.hpp -> ${result.mock_count} C++ class mock(s)`);
	};

	generateWith(RegexMockaccino, genDir, 'regex');
	generateWith(ClangMockaccino, genClangDir, 'clang');
	generateCppWith(RegexMockaccino, genDir, 'regex');
	generateCppWith(ClangMockaccino, genClangDir, 'clang');

	// Negative path: a header with a deliberate type error must surface clang's
	// diagnostics. clang still emits a partial AST (so generation succeeds for the
	// valid decls), but the backend must report clangHadErrors and the error text
	// — that is what the extension shows in its Mockaccino log.
	{
		const probeOut = fs.mkdtempSync(path.join(os.tmpdir(), 'mockaccino-clang-err-'));
		const probeContent = 'int good_fn(void);\nUndefinedType_T bad_fn(void);\n';
		const probeUri = { fsPath: path.join(srcDir, '__clang_error_probe.h'), scheme: 'file' };
		const log = console.log;
		const warn = console.warn;
		console.log = () => {};
		console.warn = () => {};
		let probe;
		try {
			probe = new ClangMockaccino(probeContent, probeUri, makeConfig(probeOut), '0.0.0-test', '', templatesDir);
			probe.mock();
		} finally {
			console.log = log;
			console.warn = warn;
		}
		if (probe.clangHadErrors !== true) {
			fail('clang error reporting: expected clangHadErrors=true for a header with an undefined type');
		}
		if (!/error:/i.test(probe.clangDiagnostics)) {
			fail(`clang error reporting: expected diagnostics to contain an error, got:\n${probe.clangDiagnostics}`);
		}
		if (!/UndefinedType_T/.test(probe.clangDiagnostics)) {
			fail(`clang error reporting: diagnostics should name the offending type, got:\n${probe.clangDiagnostics}`);
		}
		fs.rmSync(probeOut, { recursive: true, force: true });
		console.log(`  [clang] error reporting OK: "${probe.clangDiagnostics.split('\n')[0].trim()}"`);
	}
}

// --- 3. configure + build with CMake (clang) ----------------------------------
console.log('[integration] 3/5 Configuring + building (cmake + clang)...');
{
	const cfg = run('cmake', [
		'-S', integrationDir,
		'-B', buildDir,
		'-G', 'Ninja',
		'-DCMAKE_C_COMPILER=clang',
		'-DCMAKE_CXX_COMPILER=clang++',
		'-DCMAKE_BUILD_TYPE=Release',
	]);
	if (cfg.error && cfg.error.code === 'ENOENT') {
		fail('cmake not found on PATH');
	}
	if (cfg.status !== 0) {
		fail('cmake configure failed (clang/ninja missing, or no network for the GoogleTest download?)');
	}

	const build = run('cmake', ['--build', buildDir]);
	if (build.status !== 0) {
		fail('build failed');
	}
}

// --- 4. run the gmock unit tests ----------------------------------------------
console.log('[integration] 4/5 Running gmock unit tests (ctest)...');
{
	// JUnit XML report (ctest >= 3.21) for CI artifacts; harmless locally.
	const resultsDir = path.join(repoRoot, 'tests', 'integration', 'report');
	fs.mkdirSync(resultsDir, { recursive: true });
	const res = run('ctest', [
		'--test-dir', buildDir,
		'--output-on-failure',
		'--output-junit', path.join(resultsDir, 'results.xml'),
	]);
	if (res.status !== 0) {
		fail('unit tests failed');
	}
}

// --- 5. run the real game binary for a few generations ------------------------
console.log('[integration] 5/5 Running the game_of_life binary...');
{
	const exe = path.join(buildDir, isWin ? 'game_of_life.exe' : 'game_of_life');
	if (!fs.existsSync(exe)) {
		fail(`game binary not found at ${exe}`);
	}
	const res = run(exe, ['4', '0'], { shell: false });
	if (res.status !== 0) {
		fail('game binary exited non-zero');
	}
}

console.log('\n[integration] OK: mocks generated, compiled, tests passed, game ran.');
