// Mandatory integration suite orchestrator.
//
// Proves that mocks generated by Mockaccino actually compile and run: it
//   1. compiles the extension TS so out/regex_mockaccino.js exists,
//   2. runs RegexMockaccino on the dependency headers (display.h, rng.h) to emit
//      gmock mocks into integration/generated,
//   3. configures + builds the CMake project with clang (FetchContent pulls
//      GoogleTest),
//   4. runs the gmock unit tests via ctest, and
//   5. runs the real game_of_life binary for a few generations.
//
// This suite is MANDATORY and never skips: it must actually run and pass.
// Anything that stops it — a missing tool (clang/cmake/ninja/network for the
// GoogleTest download) or a genuine build/test failure — exits non-zero.

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const integrationDir = __dirname;
const repoRoot = path.resolve(integrationDir, '..');
const srcDir = path.join(integrationDir, 'src');
const genDir = path.join(integrationDir, 'generated');
const buildDir = path.join(integrationDir, 'build');
const templatesDir = path.join(repoRoot, 'templates');

const isWin = process.platform === 'win32';

function run(cmd, args, opts = {}) {
	const res = spawnSync(cmd, args, {
		stdio: 'inherit',
		shell: isWin, // resolve cmake/ctest/npx via PATH + PATHEXT on Windows
		cwd: opts.cwd || integrationDir,
		...opts,
	});
	return res;
}

function fail(message) {
	console.error(`\n[integration] FAILED: ${message}`);
	process.exit(1);
}

// --- 1. compile the extension so out/mockaccino.js is available ---------------
console.log('[integration] 1/5 Compiling extension (tsc)...');
{
	const res = run(isWin ? 'npx.cmd' : 'npx', ['tsc', '-p', '.', '--outDir', 'out'], { cwd: repoRoot });
	if (res.error || res.status !== 0) {
		fail('could not compile the extension with tsc');
	}
}

// --- 2. generate the mocks with Mockaccino ------------------------------------
console.log('[integration] 2/5 Generating mocks with Mockaccino...');
{
	const RegexMockaccino = require(path.join(repoRoot, 'out', 'regex_mockaccino'));
	fs.mkdirSync(genDir, { recursive: true });

	const makeConfig = (outputPath) => {
		const values = {
			additionalPreprocessorDirectives: '',
			ignoredFunctionNames: 'main',
			copyright: 'Copyright (c) 2026 Mockaccino integration test.',
			treatLonelyPreprocIfAsActive: true,
			skipFunctionsWithImplicitReturnType: false,
			skipStaticFunctions: true,
			skipExternFunctions: true,
			outputPath,
		};
		const cfg = { get: (k) => values[k] };
		cfg.disableDoubleMocking = true;
		return cfg;
	};

	// Silence the orchestrator's chatty logging.
	const log = console.log;
	const warn = console.warn;
	console.log = () => {};
	console.warn = () => {};
	try {
		const restore = () => {
			console.log = log;
			console.warn = warn;
		};
		for (const header of ['display.h', 'rng.h']) {
			const src = path.join(srcDir, header);
			const content = fs.readFileSync(src, 'utf8');
			const uri = { fsPath: src, scheme: 'file' };
			// One instance per header is reused for both outputs (parsing happens once).
			const generator = new RegexMockaccino(content, uri, makeConfig(genDir), '0.0.0-test', '', templatesDir);
			const mockResult = generator.mock();
			if (mockResult.result !== 0) {
				restore();
				fail(`mock generation for ${header} returned ${mockResult.result}: ${mockResult.message}`);
			}
			const stubResult = generator.stub();
			if (stubResult.result !== 0) {
				restore();
				fail(`stub generation for ${header} returned ${stubResult.result}: ${stubResult.message}`);
			}
			log(`  ${header} -> ${mockResult.mock_count} mock(s), ${stubResult.mock_count} stub(s)`);
		}
	} finally {
		console.log = log;
		console.warn = warn;
	}
}

// --- 3. configure + build with CMake (clang) ----------------------------------
console.log('[integration] 3/5 Configuring + building (cmake + clang)...');
{
	const cfg = run('cmake', [
		'-S', integrationDir,
		'-B', buildDir,
		'-G', 'Ninja',
		'-DCMAKE_C_COMPILER=clang',
		'-DCMAKE_CXX_COMPILER=clang++',
		'-DCMAKE_BUILD_TYPE=Release',
	]);
	if (cfg.error && cfg.error.code === 'ENOENT') {
		fail('cmake not found on PATH');
	}
	if (cfg.status !== 0) {
		fail('cmake configure failed (clang/ninja missing, or no network for the GoogleTest download?)');
	}

	const build = run('cmake', ['--build', buildDir]);
	if (build.status !== 0) {
		fail('build failed');
	}
}

// --- 4. run the gmock unit tests ----------------------------------------------
console.log('[integration] 4/5 Running gmock unit tests (ctest)...');
{
	const res = run('ctest', ['--test-dir', buildDir, '--output-on-failure']);
	if (res.status !== 0) {
		fail('unit tests failed');
	}
}

// --- 5. run the real game binary for a few generations ------------------------
console.log('[integration] 5/5 Running the game_of_life binary...');
{
	const exe = path.join(buildDir, isWin ? 'game_of_life.exe' : 'game_of_life');
	if (!fs.existsSync(exe)) {
		fail(`game binary not found at ${exe}`);
	}
	const res = run(exe, ['4', '0'], { shell: false });
	if (res.status !== 0) {
		fail('game binary exited non-zero');
	}
}

console.log('\n[integration] OK: mocks generated, compiled, tests passed, game ran.');
